/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;

/**
 *
 * @author Mokleters
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form(String user) {
        initComponents();
        txtAdmin.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel3.setText("FORM PELANGGAN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 20, 340, 80);

        jLabel1.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 36)); // NOI18N
        jLabel1.setText("RetroGround");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 220, 50);

        jLabel2.setFont(new java.awt.Font("Century751 BT", 0, 18)); // NOI18N
        jLabel2.setText("Karena yang jadul juga asyik!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 240, 30);

        txtAdmin.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jPanel1.add(txtAdmin);
        txtAdmin.setBounds(370, 90, 230, 30);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jLabel4.setText("Admin: ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 70, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 80, 330, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1070, 130);

        setBounds(0, 0, 974, 502);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user = null;
                new form(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAdmin;
    // End of variables declaration//GEN-END:variables
}
